<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="content-wrapper">
        <?php if ($block->getFirstName()): ?>
            <p>FirstName: <?= $block->getFirstName() ?></p>
        <?php endif; ?>
        <?php if ($block->getLastname()): ?>
            <p>Lastname: <?= $block->getLastname() ?></p>
        <?php endif; ?>
    <a href="<?= $block->getGeneratedUrlToController() ?>">Link to JSON controller</a>
</div>




